quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, OPTIONS, POST, PUT, DELETE, OPTIONS, PATCH
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with